// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxfjmioqexxbhisypwqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZmptaW9xZXh4Ymhpc3lwd3F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjE0MDksImV4cCI6MjA2NjEzNzQwOX0.tyOsgBkkYAR8JAXLFBD8rQCN_MxQcOjwxf1lUPG_Q9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);